### ISSUE TITLE
Cleanup Upstream Dependencies

### ISSUE THREAD

**Issue by mitchellwills** [RIVeR-Lab/walrus#37]
I have a bunch of stuff I need to submit/work on for external packages (not including WebRTC stuff from #8)

- [x] Release libsensors node (ros-drivers/linux_peripheral_interfaces#4)
- [x] Document libsensors node
- [x] Release ros_package_web_server
- [x] Document ros_package_web_server
- [x] Fix rqt_robot_monitor and UTF8 (ros-visualization/rqt_robot_plugins#79)
- [x] Fix ROS Diagnostics Aggregator (ros/diagnostics#17)
- [x] Release EPOS driver
- [x] Document EPOS driver
- [x] Update usb_cam to allow for better use as library (bosch-ros-pkg/usb_cam#29)
